version: '3.1'

services:

  weeklymeal-planner-db:
    image: mysql
    container_name: weeklymeal-planner-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_USERNAME: ${DEV_DB_USERNAME}
      MYSQL_PASSWORD: ${DEV_DB_PASSWORD}
      MYSQL_DATABASE: ${DEV_DB_DATABASE}